# Generated by Django 5.0.1 on 2026-01-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_inventoryitem_promocode_user_latitude_user_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
