# Generated by Django 5.0.1 on 2026-01-31 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationtask',
            name='is_router_required',
            field=models.BooleanField(default=True, help_text='Did customer choose to buy router?'),
        ),
        migrations.AddField(
            model_name='installationtask',
            name='one_time_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(default='Monthly Subscription Charge', max_length=200),
        ),
        migrations.AddField(
            model_name='plan',
            name='data_limit_gb',
            field=models.IntegerField(default=1000, help_text='Monthly Data Limit (FUP)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subscription'),
        ),
    ]
