# Generated by Django 5.0.1 on 2026-02-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_installationtask_is_router_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('LEAD', 'Lead (Pending)'), ('VERIFIED', 'Verified (Select Plan)'), ('READY_TO_INSTALL', 'Ready to Install'), ('INSTALLATION_PENDING', 'Installation Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
    ]
