# Generated by Django 5.0.1 on 2026-02-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='coordinates',
            field=models.TextField(blank=True, help_text='JSON list of [lat, lng] points for polygon', null=True),
        ),
    ]
