# Generated by Django 5.0.1 on 2026-03-04 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_area_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationtask',
            name='assigned_technical_staff',
            field=models.ForeignKey(blank=True, help_text='Technical Staff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_technical_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='installationtask',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, help_text='Field Staff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_installations', to=settings.AUTH_USER_MODEL),
        ),
    ]
