# Generated by Django 5.0.1 on 2026-03-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_installationtask_assigned_technical_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='features',
            field=models.TextField(blank=True, help_text='Comma-separated or JSON list of key features (e.g. Wi-Fi 6, Dual-Band)', null=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='hero_tagline',
            field=models.CharField(blank=True, help_text='Short catchy slogan for the router', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='specifications',
            field=models.TextField(blank=True, help_text="JSON format of specs (e.g. {'Antennas': '4', 'Ports': '4 Gigabit'})", null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='description',
            field=models.TextField(help_text='General description'),
        ),
    ]
