# Generated by Django 5.0.1 on 2026-03-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_hardware_features_hardware_hero_tagline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.TextField(blank=True, help_text='Comma-separated list of benefits', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='hero_tagline',
            field=models.CharField(blank=True, help_text='Catchy marketing phrase (e.g. Unstoppable Gaming Speed)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='recommended_hardware',
            field=models.ManyToManyField(blank=True, help_text='Hardware suggested for this plan', related_name='recommended_for_plans', to='api.hardware'),
        ),
    ]
