# Generated by Django 5.0.1 on 2026-03-07 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_plan_features_plan_hero_tagline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationtask',
            name='hardware',
            field=models.ForeignKey(blank=True, help_text='Selected Company Router', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hardware'),
        ),
        migrations.AddField(
            model_name='installationtask',
            name='own_router_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_routers/'),
        ),
        migrations.AddField(
            model_name='installationtask',
            name='own_router_mac',
            field=models.CharField(blank=True, help_text='MAC if customer brings own router', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='installationtask',
            name='own_router_model',
            field=models.CharField(blank=True, help_text='Model if customer brings own router', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='installationtask',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Selected Internet Plan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.plan'),
        ),
    ]
