# Generated by Django 5.0.1 on 2026-03-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_installationtask_hardware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_under_maintenance',
            field=models.BooleanField(default=False, help_text='Toggle to show maintenance warning to users'),
        ),
        migrations.AddField(
            model_name='area',
            name='maintenance_message',
            field=models.CharField(blank=True, help_text='Specific warning message (e.g. Fiber cut, ETA 2 hours)', max_length=255, null=True),
        ),
    ]
