# Generated by Django 5.0.1 on 2026-03-18 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_area_is_under_maintenance_area_maintenance_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='upgrade_to_plan',
            field=models.ForeignKey(blank=True, help_text='If set, paying this invoice upgrades the subscription to this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.plan'),
        ),
    ]
